# Generated by Django 3.2.4 on 2021-07-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210708_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('questions', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questionnaires',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SruveyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_responses', models.CharField(max_length=5000)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sruvey_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flavor', models.CharField(blank=True, max_length=255, null=True)),
                ('efficacy_num', models.PositiveIntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLikedTeaMap',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.users')),
            ],
            options={
                'db_table': 'user_liked_tea_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserWantTeaMap',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='polls.users')),
            ],
            options={
                'db_table': 'user_want_tea_map',
                'managed': False,
            },
        ),
    ]
