# Generated by Django 4.0.3 on 2022-05-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_buy_product',
                'managed': False,
            },
        ),
    ]
