# Generated by Django 3.1.6 on 2022-08-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_tokenblacklistblacklistedtoken_tokenblacklistoutstandingtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MypageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.CharField(db_column='class', max_length=255)),
                ('mileage', models.PositiveIntegerField()),
                ('coupon', models.PositiveIntegerField()),
                ('order_history', models.PositiveIntegerField()),
                ('delivery', models.PositiveIntegerField()),
                ('review', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mypage_info',
                'managed': False,
            },
        ),
    ]
